---
deployment:
  tasks:
    - source /home/ztlzpllpqetq/virtualenv/citystateapi/3.6/bin/activate && cd /home/ztlzpllpqetq/citystateapi
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python manage.py collectstatic --no-input
    - python manage.py migrate
    - touch tmp/restart.txt 